# PPE model config

_target_: src.models.ppe_model.PpeLightningModel

backbone: mobilenetv3 # model backbone
helmet_class: 5 # number of classes for helmet
vest_class: 5 # number of classes for vest
boots_class: 2 # number of classes for boots
lr: 0.0001 # learning rate
pretrained: true # use pretrained weights
